[build]
builder = "nixpacks"

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/health.php"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
APP_ENV = "production"
APP_DEBUG = "false"
DB_CONNECTION = "sqlite"
DB_DATABASE = "/app/database/database.sqlite"
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"
QUEUE_CONNECTION = "sync"
FILESYSTEM_DISK = "public" 